### ISSUE TITLE
ERROR: Site will not to deploy to static hosting services

### ISSUE THREAD

**Issue by jordanlambrecht** [jordanlambrecht/pb-oct-2022#21]

**Comment by jordanlambrecht** [comment]
```
2021-11-24T18:29:03.980773845Z => Initializing build
2021-11-24T18:29:03.997991458Z => Retrieving source code to /workspace
2021-11-24T18:29:04.013003358Z => Selecting branch "main"
2021-11-24T18:29:09.969344131Z => Checking out commit "e70b8434d3144704cc229451bd27b46e3825cba1"
2021-11-24T18:29:10.690327233Z => Got source_dir: /
2021-11-24T18:29:10.701788490Z => Using workspace root /workspace
2021-11-24T18:29:10.722261595Z 
2021-11-24T18:29:10.722358098Z => Building app using buildpacks
2021-11-24T18:29:10.832181700Z => Configuring custom build command to be run at the end of the build:
2021-11-24T18:29:10.843274150Z      npm run build
2021-11-24T18:29:11.135168427Z => Running buildpack detection
2021-11-24T18:29:11.135194790Z 
2021-11-24T18:29:11.543658844Z heroku/nodejs-engine  0.5.0
2021-11-24T18:29:11.543680796Z digitalocean/node     0.3.4
2021-11-24T18:29:11.543776760Z digitalocean/procfile 0.0.3
2021-11-24T18:29:11.543859427Z digitalocean/custom   0.1.0
2021-11-24T18:29:11.585756651Z 
2021-11-24T18:29:11.585774308Z For documentation on the buildpacks used to build your app, please see:
2021-11-24T18:29:11.585799298Z    Node.js: https://do.co/apps-buildpack-node
2021-11-24T18:29:11.778080190Z 
2021-11-24T18:29:11.778391935Z => Checking for cache from a previous build
2021-11-24T18:29:13.351348164Z Previous image with name <registry-uri-0> not found
2021-11-24T18:29:14.042526097Z Layer cache not found
2021-11-24T18:29:15.771127547Z Layer cache not found
2021-11-24T18:29:16.207315715Z 
2021-11-24T18:29:16.207383146Z => Building app
2021-11-24T18:29:16.207390647Z 
2021-11-24T18:29:16.306188995Z ---> Node.js Buildpack
2021-11-24T18:29:16.312801896Z ---> Installing toolbox
2021-11-24T18:29:16.325549984Z ---> - jq
2021-11-24T18:29:17.072066226Z ---> - yj
2021-11-24T18:29:17.723167419Z ---> Getting Node version
2021-11-24T18:29:17.739341821Z ---> Resolving Node version
2021-11-24T18:29:20.264689514Z ---> Downloading and extracting Node v12.22.7
2021-11-24T18:29:33.686543042Z ---> Parsing package.json
2021-11-24T18:29:34.482630294Z ---> No file to start server
2021-11-24T18:29:34.482654044Z ---> either use 'docker run' to start container or add index.js or server.js
2021-11-24T18:29:34.505375071Z Project contains package-lock.json, using npm
2021-11-24T18:29:34.809474344Z Using npm v6.14.15. To configure a different version of npm, set the engines.npm property in package.json.
2021-11-24T18:29:34.809500349Z   See https://do.co/apps-buildpack-node for further instructions.
2021-11-24T18:29:34.809879549Z Installing node_modules using npm (from package-lock.json)
2021-11-24T18:29:35.095377753Z Running npm ci
2021-11-24T18:29:35.095397026Z 
2021-11-24T18:29:53.596806071Z 
2021-11-24T18:29:53.596840002Z > core-js@3.19.1 postinstall /workspace/node_modules/core-js
2021-11-24T18:29:53.596846408Z > node -e "try{require('./postinstall')}catch(e){}"
2021-11-24T18:29:53.596850114Z 
2021-11-24T18:29:53.741745641Z [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
2021-11-24T18:29:53.741775128Z 
2021-11-24T18:29:53.741781061Z [96mThe project needs your help! Please consider supporting of core-js:[0m
2021-11-24T18:29:53.741788450Z [96m>[94m https://opencollective.com/core-js [0m
2021-11-24T18:29:53.741794033Z [96m>[94m https://patreon.com/zloirock [0m
2021-11-24T18:29:53.741798644Z [96m>[94m https://paypal.me/zloirock [0m
2021-11-24T18:29:53.741802419Z [96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
2021-11-24T18:29:53.741807068Z 
2021-11-24T18:29:53.741810807Z [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2021-11-24T18:29:53.741832736Z 
2021-11-24T18:29:53.838905282Z 
2021-11-24T18:29:53.838939819Z > esbuild@0.13.15 postinstall /workspace/node_modules/esbuild
2021-11-24T18:29:53.838961807Z > node install.js
2021-11-24T18:29:53.838967760Z 
2021-11-24T18:29:54.887100521Z added 704 packages in 19.023s
2021-11-24T18:29:54.911386348Z 
2021-11-24T18:30:00.669807101Z Running custom build command: npm run build
2021-11-24T18:30:01.063463001Z 
2021-11-24T18:30:01.063494791Z > pb-oct-22@0.0.12 build /workspace
2021-11-24T18:30:01.063501566Z > vite build 
2021-11-24T18:30:01.063506420Z 
2021-11-24T18:30:01.437925404Z vite v2.6.14 building for production...
2021-11-24T18:30:01.511580036Z transforming...
2021-11-24T18:30:01.693727492Z âœ“ 12 modules transformed.
2021-11-24T18:30:01.694641446Z Could not resolve './pages/Services/Services-Animation' from src/App.jsx
2021-11-24T18:30:01.696093072Z error during build:
2021-11-24T18:30:01.696101033Z Error: Could not resolve './pages/Services/Services-Animation' from src/App.jsx
2021-11-24T18:30:01.696106591Z     at error (/workspace/node_modules/rollup/dist/shared/rollup.js:158:30)
2021-11-24T18:30:01.696110586Z     at ModuleLoader.handleResolveId (/workspace/node_modules/rollup/dist/shared/rollup.js:22345:24)
2021-11-24T18:30:01.696114040Z     at /workspace/node_modules/rollup/dist/shared/rollup.js:22319:26
2021-11-24T18:30:01.696117037Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-11-24T18:30:01.711626353Z npm ERR! code ELIFECYCLE
2021-11-24T18:30:01.711866793Z npm ERR! errno 1
2021-11-24T18:30:01.714765970Z npm ERR! pb-oct-22@0.0.12 build: `vite build `
2021-11-24T18:30:01.715018178Z npm ERR! Exit status 1
2021-11-24T18:30:01.715186016Z npm ERR! 
2021-11-24T18:30:01.715386576Z npm ERR! Failed at the pb-oct-22@0.0.12 build script.
2021-11-24T18:30:01.715590572Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-11-24T18:30:01.721830890Z 
2021-11-24T18:30:01.721847950Z npm ERR! A complete log of this run can be found in:
2021-11-24T18:30:01.722003666Z npm ERR!     /home/apps/.npm/_logs/2021-11-24T18_30_01_716Z-debug.log
2021-11-24T18:30:01.729919986Z building: exit status 1
2021-11-24T18:30:01.731315183Z [31;1mERROR: [0mfailed to build: exit status 1
2021-11-24T18:30:05.824457378Z 
2021-11-24T18:30:05.824567943Z For documentation on the buildpacks used to build your app, please see:
2021-11-24T18:30:05.824643882Z    Node.js: https://do.co/apps-buildpack-node
2021-11-24T18:30:05.826116935Z 
2021-11-24T18:30:05.826436482Z [31m ! Build failed (145)[0m
```
